# Questo set di tasks viene eseguito solo sull'host master.
- hosts: masters
  become: yes
  tasks:
    # Inizializza il cluster Kubernetes con kubeadm.
    - name: Initialize Kubernetes Master
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 | tee /home/your_user/kubeadm_init_output
      args:
        # Questa linea fa sì che il task venga saltato se il file /etc/kubernetes/admin.conf esiste già.
        creates: /etc/kubernetes/admin.conf
        # Scarica lo script di installazione di Helm.
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    # Esegui lo script di installazione di Helm.
    - name: Install Helm
      command: /tmp/get_helm.sh

    # Aggiungi il repository di Helm.
    - name: Add Helm repository
      command: helm repo add stable https://charts.helm.sh/stable
      become: yes
      become_user: root
