# Questo set di tasks viene eseguito solo sugli host worker.
- hosts: workers
  become: yes
  tasks:
    # Estrae il comando 'kubeadm join' dal nodo master.
    - name: Extract join command from master
      shell: 'ssh your_user@master_ip "cat /home/your_user/kubeadm_init_output | grep \"kubeadm join\" "'
      register: join_command
    # Esegue il comando 'kubeadm join' per far unire il nodo worker al cluster.
    - name: Join cluster
      shell: "{{ join_command.stdout }}"


  